platform :ios, '9.0'

target 'iOS Trivia' do
  use_frameworks!

  # Autolayout
  pod 'SnapKit'

  # Firebase / Networking
  pod 'Firebase/Core'
  pod 'Moya'

  # Caching
  pod 'UserDefaultsStore'

end
